# -*- coding: utf-8 -*-
"""Ketelyn Stinguel_Ag5_DS_I.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N61eCPzv41hyJlFqQU37O5aQJvsHGkKI
"""

print("=== Calculadora de Consumo Elétrico ===")

aparelho = input("Nome do aparelho: ")
potencia = float(input("Potência do aparelho (em watts): "))
horas_dia = float(input("Horas de uso diário: "))

consumo_mensal = (potencia * horas_dia * 30) / 1000  # kWh/mês
custo_kwh = 0.75
custo_estimado = consumo_mensal * custo_kwh

print("\n--- Resultado ---")
print(f"Aparelho: {aparelho}")
print(f"Consumo estimado: {consumo_mensal:.2f} kWh/mês")
print(f"Custo estimado: R$ {custo_estimado:.2f}/mês")